### ISSUE TITLE
Deduping 'og:image' not working.

### ISSUE THREAD

**Issue by jcdb95** [harlan-zw/unhead#11]
### Describe the bug

Deduping 'og:image' is not working only by the property name, It works only if you add `key` to it, then it gets deduplicated correctly.

For example if you want to have add a new 'og:image' at the App.vue as a fallback and then for a child route you add 'og:image', it will take both, unless you provide a key.

## App.vue
```
useHead({
  title: "Dedup image bug",
  meta: [
    {
      name: "description",
      content: "My page description",
    },
    {
      name: "og:image",
      content: "/public/share_image.jpg",
    },
  ],
});
```

## AboutView.vue

```
useHead({
  title: "About us",
  meta: [
    {
      name: "description",
      content: "My about us description",
    },
    {
      name: "og:image",
      content: "/public/car.jpg",
    },
  ],
});

```

## Result

![image](https://user-images.githubusercontent.com/26585143/202233701-c75125d3-42b8-4782-8826-7239a4452bc1.png)

Also, what we have encountered with this workaround is that if you start navigating around, the reactivity of the image is gone and you don't have even the fallback coming from `App.vue`

In the following repo you can find that on `App.vue` I set an 'og:image' and on the `/about` view, I set a new one and if you search for 'og:image' on the elements, you will see both.

### Reproduction

https://github.com/jcdb95/dedup-image-bug

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 104.47 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @jcdb95 

Thanks for the detailed issue. Firstly, the reactivity isn't working because you're using the `unhead` dependency, you should use `@unhead/vue`.

The main issue I'll push up a fix shortly for

**Comment by harlan-zw** [comment]
Should be fixed in 1.0.1

**Comment by paraboul** [comment]
Hey @harlan-zw ,

I'm still running into this issue specifically on `og:image` combined with a `v-if`.
Here is the current behaviour :

The main App component has a generic `og:image`.
✅ A sub view defines a new `og:image`, it's replaced properly.
❌ A sub view defines a new `og:image` with a v-if condition : it's duplicated
✅ A sub view defines a new `og:image`, with a v-if condition and the same `key` as the one from the App component : it's replaced.

**Comment by harlan-zw** [comment]
Hey @paraboul, thanks for the details.

Sounds quite particular, would it be possible to make a new issue with a StackBlitz reeproduction? :pray:
